### ISSUE TITLE
Lpo MA NA (16F04, 16F10)

### ISSUE THREAD

**Issue by cheuk879** [silnrsi/font-shimenkan#10]
The following nasal variants are needed for [lpo]:

16F04: ![plrd-16f04-round](https://user-images.githubusercontent.com/10625598/41576767-c5cda85a-73bb-11e8-8206-fa46cf6a78a8.gif) -- The top & bottom are round like the mirror opposite of the Latin letter 'C'.
16F10: ![plrd-16f10-round](https://user-images.githubusercontent.com/10625598/41576812-fae6aa96-73bb-11e8-81af-747ba02c7a50.gif) -- The top & bottom are round like the Latin letter 'C'.

**Comment by jvgaultney** [comment]
Working now
![image](https://user-images.githubusercontent.com/4226750/53868613-59a0fd80-3fee-11e9-82b5-70349083aa19.png)
