### ISSUE TITLE
Flat-sided NNA NGA (16F14, 16F23)

### ISSUE THREAD

**Issue by cheuk879** [silnrsi/font-shimenkan#14]
The following nasal variants are needed for both subgroups of [ywq]; [lpo] only needs 16F23:

16F14: ![plrd-16f14-flat](https://user-images.githubusercontent.com/10625598/41577322-cbce9e1e-73be-11e8-9d15-4c56a08fd8f6.gif)
16F23: ![plrd-16f23-flat](https://user-images.githubusercontent.com/10625598/41576830-16a76220-73bc-11e8-8620-1aad55164e37.gif)

The sides are flat & corners round.

**Comment by jvgaultney** [comment]
Working now for lpo ywqa ywqb
![image](https://user-images.githubusercontent.com/4226750/53868472-06c74600-3fee-11e9-83e6-a230cb489265.png)
