### ISSUE TITLE
Dotted Variants for [hmdd]

### ISSUE THREAD

**Issue by cheuk879** [silnrsi/font-shimenkan#20]
All warted initials have an upper-right dot in lieu of the wart in the [hmdd] tradition.  There are 24 of them in total.  A code point list is provided here:

16F01, 16F05, 16F09, 16F0B, 16F0F, 16F11, 16F15, 16F17, 16F19, 16F1B, 16F1D, 16F1F,
16F22, 16F24, 16F29, 16F2B, 16F2D, 16F2F, 16F36, 16F38, 16F3C, 16F3E, 16F41, 16F44

And here's an example of the dot:

![plrd-dot-eg](https://user-images.githubusercontent.com/10625598/41583962-97dab218-73d8-11e8-964c-41fcb0864b4f.gif)

**Comment by jvgaultney** [comment]
Actually the following glyphs should be excluded, as the default for them already has the dot in place fo the [hmdd] variants: u16F05, u16F11, u16F15, u16F24. https://github.com/silnrsi/font-shimenkan/issues/19

**Comment by cheuk879** [comment]
Pls see new comment in #19.

**Comment by jvgaultney** [comment]
And my further comment in #19.

**Comment by jvgaultney** [comment]
Working now
![image](https://user-images.githubusercontent.com/4226750/53869624-79d1bc00-3ff0-11e9-92c7-1db48842fbf7.png)
