### ISSUE TITLE
Hmd-D Vowels (16F5E, 16F5F)

### ISSUE THREAD

**Issue by cheuk879** [silnrsi/font-shimenkan#22]
The following flat-top variants are needed for [hmdd]:

16F5E: ![plrd-16f5e-flat](https://user-images.githubusercontent.com/10625598/41584166-26c7fce2-73d9-11e8-8e30-a28a0598c51c.gif)
16F5F: ![plrd-16f5f-flat](https://user-images.githubusercontent.com/10625598/41584212-48e481a6-73d9-11e8-92f0-1567f108d3c1.gif)

The top is flat with a pointed angle on the left.

**Comment by jvgaultney** [comment]
Working now
![image](https://user-images.githubusercontent.com/4226750/53887968-45272a00-401b-11e9-959a-398f3ef80bc5.png)
