### ISSUE TITLE
Asp + retrograde waist vowel spacing affects intersyllable spacing

### ISSUE THREAD

**Issue by jvgaultney** [silnrsi/font-shimenkan#24]
When a waist height vowel is tucked inside a consonant, but the asp remains unmoved, it can affect the intersyllable spacing, as in:

![image](https://user-images.githubusercontent.com/4226750/41879384-4fc1d152-78d1-11e8-97f9-5f65eb4783f1.png)

**Comment by mhosken** [comment]
Only adds some 2500 rules :(
