### ISSUE TITLE
[sfm, hmz, hmd] Three features needed to move asp before consonant

### ISSUE THREAD

**Issue by jvgaultney** [silnrsi/font-shimenkan#27]
We need three features that will move the asp to appear before the consonant:

Left aspiration MA - needs ligature u16F04_u16F51  [sfm][hmz]
Left aspiration NA - needs ligature u16F10_u16F51  [sfm][hmz][hmd]
Left aspiration NGA - needs ligature u16F23_u16F51  [hmz][hmd]

These need to be separate features as each language uses a different combination of them.

**Comment by cheuk879** [comment]
left asp NGA only applies to [hmz].  ([hmd] prefers to have it on the right.)

**Comment by jvgaultney** [comment]
Noted and changed in my separate planning doc

**Comment by jvgaultney** [comment]
Working now for sfm hmz

![image](https://user-images.githubusercontent.com/4226750/53868185-61ac6d80-3fed-11e9-86f4-be7aa0f1c156.png)

**Comment by cheuk879** [comment]
Asp still rendered on RHS with finals at F, K, W, H:
![plrd-asp-left](https://user-images.githubusercontent.com/10625598/58738466-1b379680-83c3-11e9-8425-d8c5b1a385ea.png)

**Comment by cheuk879** [comment]
@jvgaultney : pls reopen issue.  Couldn't find any button or link to do that myself.

**Comment by mhosken** [comment]
Where the apostrophe precedes a consonant, is it acting as a nasaliser as in a variant of U+16F50 or as aspiration and so is U+16F51?

My suspicions are that this is a variant of U+16F50, which we don't but very much should support. I am worried that people are typing a U+16F51 and expecting it to work. I'm thinking we should insert a dotted circle if someone types anything other than a consonant before a U+16F51.
