### ISSUE TITLE
16F81 and 16F82 do not respond to MIAO TONE RIGHT or ABOVE

### ISSUE THREAD

**Issue by Nathan22Miles** [silnrsi/font-shimenkan#29]
For example the following sequence 16F0A 16F82 16F90 shows vowel sitting on the base line.

I am using Paratext 8.1 Alpha (8.1.23.13), I don't know if Paratext is rendering this via Graphite or Open Type (Tom Hindle probably could tell us). I am using ShimekanTestBook-Regular.ttf from Fonts_Shimenkan_results_91.zip.

Other than this AFAICT the font appears to be rendering the text beautimously! Thank you for all your work on this.

**Comment by mhosken** [comment]
fix pushed. But worth another look. I'll close this ticket and you can open another one on anything you find.
