### ISSUE TITLE
Odd consonant lift

### ISSUE THREAD

**Issue by Nathan22Miles** [silnrsi/font-shimenkan#30]
![image](https://user-images.githubusercontent.com/4006180/48289907-ac025100-e436-11e8-8303-5cbb71a886b9.png)

The sequence 16F79 16F0E 16F7B 16F90 from the Gan Yi text causes consonant to be lifted. Oddly if you remove the tone character or make it top position the shift goes away.

**Comment by Nathan22Miles** [comment]
[GanYiLift.txt](https://github.com/silnrsi/font-shimenkan/files/2567618/GanYiLift.txt)

Example text

**Comment by mhosken** [comment]
Is this real use case data? Having a floating vowel isn't expected at the start of a cluster, so I would argue garbage in garbage out for this. I think what is meant here is to use U+16F4F (as per https://www.unicode.org/L2/L2017/17345-n4845-miao-add.pdf). Notice that it is stored after the consonant, before any vowels.

**Comment by mhosken** [comment]
Seems fixed
