### ISSUE TITLE
[sfm, ygp] Make all vowels align to right of consonant

### ISSUE THREAD

**Issue by mhosken** [silnrsi/font-shimenkan#32]
The following changes are requested for Bai Yi (ygp?).
![changes1](https://lh3.googleusercontent.com/5RA_VNFHpXH3chNtwQRZebzsbBn_AvPvazllAnTBCvuv76pWvgOUpN-aFUWGqRrwtYJWEE_HHLnNP2VX1cAZgHnjZW2bxBleoCBAqncWEggOol8v1uNePi4Adeok-LfLXA3whuBH)

**Comment by mhosken** [comment]
Flush right positioning

**Comment by cheuk879** [comment]
Yes, this is ygp (pls. add to subject line), & this is indeed their request.

**Comment by cheuk879** [comment]
2019-06-25: **sfm** has also confirmed that they do not want any CV kerning.  Pls. add both language codes ([sfm][ygp]) to subject line.

**Comment by jvgaultney** [comment]
OK - making sfm untucked/unkerned will require adding that language to those that connect SR-SBR and FR-FBR instead of S-SB and F-FB (ygo, lpo). It will also require resetting the position of all E and K APs to make them flush right.

**Comment by mhosken** [comment]
It will also involve significant refactoring of the OT code to not tuck
under the aspiration.

**Comment by jvgaultney** [comment]
It's now confirmed that [lpo] should not be flush right (kerned/tucked), so we'll need to remove them from that feature.

**Comment by jvgaultney** [comment]
E & K anchors are now flush right, so that should now work. Getting the E & K to not tuck under the aspiration may require further OT refactoring work. Please test and let us know if this is working for you.

**Comment by cheuk879** [comment]
Per build 242, [sfm] V at K/F still tucked under asp:
![plrd-test-sfm-kern-asp-v-err](https://user-images.githubusercontent.com/10625598/62673608-ec561780-b953-11e9-93d6-5d749b1846b0.png)

**Comment by mhosken** [comment]
This is working as intended. Clearly we do not understand what the problem is. Why are these not acceptable?

**Comment by cheuk879** [comment]
[sfm] users do not want any kerning/tuck-in at all whatever the tone pos & whether there's asp.  (See Future Plan doc & the pictures we sent you on 25 Jun.)  @jvgaultney also commented on 28 Jun above that this might require further OT work, though the positions in question here are K & F.  Is this something that can be fixed for v1.0?

**Comment by cheuk879** [comment]
For your convenience here are the combos in the pix we sent you plus another one:
![plrd-sfm-nokern-noasp](https://user-images.githubusercontent.com/10625598/62745502-0f3e0580-ba00-11e9-9aee-fa60ccff8953.png)
![plrd-sfm-nokern-asp1](https://user-images.githubusercontent.com/10625598/62745509-16651380-ba00-11e9-8724-bd605367e878.png)
![plrd-sfm-nokern-asp2](https://user-images.githubusercontent.com/10625598/62745514-19600400-ba00-11e9-9282-551da9b48b8c.png)
![plrd-sfm-nokern-asp3](https://user-images.githubusercontent.com/10625598/62745518-1bc25e00-ba00-11e9-8fe6-9a675b935e90.png)

**Comment by cheuk879** [comment]
And [ygp] desire the same: no tucking even under asp:
![plrd-ygp-nokern](https://user-images.githubusercontent.com/10625598/62759387-fcdebe80-ba35-11e9-85ed-61b7168e51be.png)

**Comment by cheuk879** [comment]
Per build 245, [sfm] & [ygp] still have V@K/F tucked under asp.  V should not go under, but its LHS should align with RHS of asp.

**Comment by cheuk879** [comment]
Have opened Issue #72 to deal with various V alignments with asp.  Is it better to continue this case over there (noting that V is already aligned to right of C w/o asp)?
