### ISSUE TITLE
Asp + 16F60, 16F73, or 16F74 + Tone Right position results in vowel in upper right

### ISSUE THREAD

**Issue by kienwt** [silnrsi/font-shimenkan#36]
See image from LibreOffice 6.1.5.2 below for comparisons. Attached txt file with tests.
[16F60 16F73 16F74.txt](https://github.com/silnrsi/font-shimenkan/files/2940785/16F60.16F73.16F74.txt)

![image](https://user-images.githubusercontent.com/18396131/53951184-d7f1c280-4108-11e9-855d-dd4ecff0eb25.png)

**Comment by mhosken** [comment]
I don't understand the actual issue here. Please can you explain. It looks fine to me.

**Comment by kienwt** [comment]
> I don't understand the actual issue here. Please can you explain. It looks fine to me.
Under "with aspiration", the first example should be positioned at waist right, same position as second example. It only occurs with the aspiration.

**Comment by kienwt** [comment]
Just downloaded fonts with the latest changes and it is resolved now.

**Comment by kienwt** [comment]
This renders differently in Notepad and LibreOffice. Images below.

![image](https://user-images.githubusercontent.com/18396131/54342750-3c1c0580-4678-11e9-903e-37606f5731fb.png)

![image](https://user-images.githubusercontent.com/18396131/54342790-548c2000-4678-11e9-8c7a-e36ebefefb4a.png)

![image](https://user-images.githubusercontent.com/18396131/54342859-7d141a00-4678-11e9-9105-62ea913269f9.png)

**Comment by mhosken** [comment]
The harfbuzz in LibreOffice is old and doing cursive attachment backwards.

**Comment by mhosken** [comment]
Are you getting any shaping on libreoffice? I'm not getting anything, even on 6.3.0 alpha.

**Comment by kienwt** [comment]
> Are you getting any shaping on libreoffice? I'm not getting anything, even on 6.3.0 alpha.

Yes, 6.1.5.2 on Windows 10.

**Comment by mhosken** [comment]
BTW please include raw text of test strings. It's very difficult to cut and paste for testing from a graphic ;)

**Comment by mhosken** [comment]
Seems to be working in b47c86e5.

**Comment by kienwt** [comment]
> BTW please include raw text of test strings. It's very difficult to cut and paste for testing from a graphic ;)

Attached raw text
[reopened.txt](https://github.com/silnrsi/font-shimenkan/files/3151287/reopened.txt)

**Comment by kienwt** [comment]
Still seeing this with [b47c86e](https://github.com/silnrsi/font-shimenkan/commit/b47c86e530901e49e8735e4582b9ba7b2c9389f4)

**Comment by mhosken** [comment]
I see it on 6.1.5.2 on Linux. But it works fine on my development build 6.3.0.0.alpha0+ So probably due to a difference in Harfbuzz version.

**Comment by kienwt** [comment]
Also displays the same way in PT8.0.100.75

**Comment by mhosken** [comment]
How about libo 6.2? I tried the version of harfbuzz (1.8.4) used in both libo 6.1 and 6.2 and it seems to work just fine.

**Comment by mhosken** [comment]
OK I've isolated the bug to not being able to do both old style and new style of cursive attachment in the same font. And yes it's all about the version of harfbuzz involved. So libo 6.2.x isn't going to work either. I'm stuck in that FEA doesn't allow me to specify more than one lookup on a glyph in a contextual rule. Thinking about this...

**Comment by mhosken** [comment]
fixed? in e14e21e0 It was just the waist tall vowels?

**Comment by kienwt** [comment]
this is fixed
