### ISSUE TITLE
Asp + 2 vowels results in aspiration mark touching some consonants

### ISSUE THREAD

**Issue by kienwt** [silnrsi/font-shimenkan#38]
See image from LibreOffice 6.1.5.2 below for comparisons. Attached txt file with tests.

[aspr-touching-consonants.txt](https://github.com/silnrsi/font-shimenkan/files/2941083/aspr-touching-consonants.txt)

![image](https://user-images.githubusercontent.com/18396131/53955079-f9f04280-4112-11e9-806d-6e92d66f43bf.png)

**Comment by mhosken** [comment]
Looks good now
