### ISSUE TITLE
Add [ywq] glyph variant for 16F2F 

### ISSUE THREAD

**Issue by kienwt** [silnrsi/font-shimenkan#39]
This was done for MiaoUnicode but I don't see a corresponding glyph in font-shimenkan. u16F_2F_.dot.glif has the dot in a different location.

From https://github.com/silnrsi/MiaoUnicode/issues/17
This is the glyph shape:
![32499935-eb151c86-c40e-11e7-835e-d0813ee67c1b](https://user-images.githubusercontent.com/18396131/57346047-af755b80-717f-11e9-832b-30c95daf765a.gif)

**Comment by jvgaultney** [comment]
According to our spec the .dot forms (including u16F2F.dot) are only in use for [hmdd]. So we'll have to create a new glyph for [ywq] (u16F2F.ywqa), and get the OT working for it. The new substitution can be combined with the Zig-zag Ywq-A ZHA (16F35.ywqa) feature. I've added it to our list to do.

**Comment by jvgaultney** [comment]
Would require new glyph but no changes to OT code as lookup is based on suffix.
