### ISSUE TITLE
Narrow MA NA (16F04, 16F10)

### ISSUE THREAD

**Issue by cheuk879** [silnrsi/font-shimenkan#4]
The following nasal variants are needed for [ygp], [ywq-A], & [ywq-B]:

16F04: ![plrd-ygp-ywq-16f04](https://user-images.githubusercontent.com/10625598/41574208-2aa20e1e-73b3-11e8-8083-d79f8e52dd01.gif) -- narrow, like the mirror opposite of 16F50.
16F10: ![plrd-ygp-ywq-16f10](https://user-images.githubusercontent.com/10625598/41574305-aee188f8-73b3-11e8-8948-36c875d18d32.gif) -- narrow like 16F50.

**Comment by jvgaultney** [comment]
Glyphs now added

**Comment by jvgaultney** [comment]
Working now for ygp
![image](https://user-images.githubusercontent.com/4226750/50685173-13d8b080-1010-11e9-879c-6fb896f74e7b.png)

**Comment by jvgaultney** [comment]
Working now for ywqa ywqb ygp
