### ISSUE TITLE
[ywq] Shorten right serif of 16F31

### ISSUE THREAD

**Issue by kienwt** [silnrsi/font-shimenkan#40]
They request that it look more like the first glyph from BlkYi3

![16F31](https://user-images.githubusercontent.com/18396131/57346896-f7e24880-7182-11e9-8719-18b0023b860b.PNG)

**Comment by jvgaultney** [comment]
I can shorten it a little bit, but the serif already gets proportionally shorter as the weight increases:
![image](https://user-images.githubusercontent.com/4226750/57387916-1eb67400-71af-11e9-8e9b-6b51a0223dcf.png)
Any change would also need to affect u16F0C, as the two should visually match. Here is the current Book weight:
![image](https://user-images.githubusercontent.com/4226750/57388126-7d7bed80-71af-11e9-899f-fc7714a596b9.png)
Here's a compromise that keeps the serif from visually disappearing in the light and heavy weights but still shortens it slightly:
![image](https://user-images.githubusercontent.com/4226750/57388457-1b6fb800-71b0-11e9-997e-15aa52ba6457.png)
Would that be acceptable?
