### ISSUE TITLE
[ywq] prefers non-flat versions of 16F14 and 16F23

### ISSUE THREAD

**Issue by kienwt** [silnrsi/font-shimenkan#42]
Team prefers non-flat versions of 16F14 and 16F23 as configured in Shimenkan Test
![16F14_16F23](https://user-images.githubusercontent.com/18396131/57348130-9375b800-7187-11e9-80f7-7de4ece322c3.PNG)

**Comment by jvgaultney** [comment]
This directly contradicts issue #14 . The change will need to be made in the OT code to remove the Flat sided NNA NGA feature for [ywq-a]. Without confirmation of [ywq-b] use we won't need to change it there. Can you confirm that this change is truly needed, despite the request in #14 ?

**Comment by mhosken** [comment]
If we decided to go this way, just turn off lookup lig_flat in ywqa.

**Comment by cheuk879** [comment]
Per their confirmation on 2019-06-11, users have indeed changed their mind over this.  They now prefer the default curved shapes (2nd row), & this is their **final** decision.

**Comment by jvgaultney** [comment]
OK with me to go ahead with this now that it's confirmed.
