### ISSUE TITLE
Asp overlaps with 16F64 in head position

### ISSUE THREAD

**Issue by kienwt** [silnrsi/font-shimenkan#43]
Raw text
[Asp_16F64.txt](https://github.com/silnrsi/font-shimenkan/files/3156423/Asp_16F64.txt)

Image from LO 6.1.5.2
![Asp_16F64](https://user-images.githubusercontent.com/18396131/57362266-034c6880-71b1-11e9-8670-26608d56ce5d.PNG)

**Comment by mhosken** [comment]
How would you like this resolved? Move the vowel right or the aspiration down?

**Comment by kienwt** [comment]
Hmd team would like vowel moved right.
