### ISSUE TITLE
[ywq] Use smaller versions of vowels at head position

### ISSUE THREAD

**Issue by jvgaultney** [silnrsi/font-shimenkan#46]
Use smaller versions of vowels at head position (ywq-a only). Duplicate all .mark vowels, rename them to .smark, shrink them in the same proportion as the .ycmp vowels in MiaoUnicode, adjust APs. Then add OT lookup to do the substitution.

**Comment by cheuk879** [comment]
User preference has been for finals at all positions to have the same size.  They confirmed on 2019-06-11 that this had not changed & would not change in the future.  IOW, they do NOT want finals to be smaller at head position.  Issue can be closed.
