### ISSUE TITLE
[sfm] Shimenkan MAS -  Asp + vowel + 16F8F - vowel not positioned properly

### ISSUE THREAD

**Issue by kienwt** [silnrsi/font-shimenkan#48]
Raw text
[sfm-raw-text-Shimenkan_MAS-with-aspiration-mark.txt](https://github.com/silnrsi/font-shimenkan/files/3186737/sfm-raw-text-Shimenkan_MAS-with-aspiration-mark.txt)

As displayed in LibreOffice
![sfm-Shimenkan_MAS-with-aspiration-mark](https://user-images.githubusercontent.com/18396131/57849102-10023980-780d-11e9-81ad-403d7d626f3f.PNG)

**Comment by kienwt** [comment]
Verified fixed in https://github.com/silnrsi/font-shimenkan/commit/8033cd620cd6c76198c8bb2ec73dbd2d0c46582e

**Comment by kienwt** [comment]
@cheuk879 points out that the vowel is positioned on a different level, image below.
![sfm-Shimenkan_MAS-with-aspiration-mark2](https://user-images.githubusercontent.com/18396131/58697986-f1836d00-83cc-11e9-8a7b-8d1ba17dafb0.PNG)

**Comment by mhosken** [comment]
Please review. I think this is fixed.

**Comment by kienwt** [comment]
Without aspiration, the vowel is still positioned slightly higher
![image](https://user-images.githubusercontent.com/18396131/61428308-6ad01400-a8d6-11e9-91da-e67a4c6e6a31.png)

**Comment by mhosken** [comment]
I agree. Sorry I messed up setting the language. Fix coming.
