### ISSUE TITLE
Ygp NNA NGA (16F14, 16F23)

### ISSUE THREAD

**Issue by cheuk879** [silnrsi/font-shimenkan#5]
The following nasal variants are needed for [ygp]:

16F14: ![plrd-ygp-16f14](https://user-images.githubusercontent.com/10625598/41574833-292ed048-73b4-11e8-86c8-4a7f96464bc6.gif) -- Narrower, w/o flat bottom; begins with a left-pointed loop.
16F23: ![plrd-ygp-16f23](https://user-images.githubusercontent.com/10625598/41574545-e2d0ae96-73b3-11e8-9426-96cff264e460.gif) -- Narrower, w/o flat top; ends with a left-pointed loop.

**Comment by jvgaultney** [comment]
I'm still not sure what a 'sesame loop' is. Here is the 'normal': 

![image](https://user-images.githubusercontent.com/4226750/41585177-3184d08e-73a1-11e8-9869-70c6039ed2fb.png)

Do you mean that the loop isn't supposed to loop back on itself? That's a very subtle difference that won't really be visible in the heavier weights. Making the letter narrower will already force me to change the loop join, so I can do that. I'm just confused by the 'sesame' term.

**Comment by jvgaultney** [comment]
Working now when language is set to ygp:
![image](https://user-images.githubusercontent.com/4226750/50685108-da07aa00-100f-11e9-9ade-7b2b8aa1f929.png)
