### ISSUE TITLE
[sfm] Shimenkan MAS - Team requests vowel combinations tucked in E and K positions

### ISSUE THREAD

**Issue by kienwt** [silnrsi/font-shimenkan#51]
Raw text
[raw-request-kerning.txt](https://github.com/silnrsi/font-shimenkan/files/3221565/raw-request-kerning.txt)

Current positioning
![CC35E9441709CCF642B1EC7A0640979B](https://user-images.githubusercontent.com/18396131/58391314-fc09d380-8067-11e9-8674-b1b145603d66.jpg)

**Comment by mhosken** [comment]
I do not recommend trying to tuck the K position. There is liable to be clashes. See zhong. Also zhuei/zhuo would be really close. Or we can move K down. Please review implications with others and confirm.

**Comment by cheuk879** [comment]
2019-06-25: Users have confirmed they do **not** want any kerning or tuck-in at any position.  Issue can be closed.
