### ISSUE TITLE
[lpo] 16F72, 16F7E loop & tail adjustments

### ISSUE THREAD

**Issue by cheuk879** [silnrsi/font-shimenkan#52]
![plrd-lpo-9-6](https://user-images.githubusercontent.com/10625598/58523441-af1a2000-8181-11e9-9501-3ea8e22b6574.png)
Top row shows current shapes in Taogu.  Users want shapes in the bottom row.  In particular, the loop needs to be a circle instead of an oval, & the tail needs to be more straight & slanted more clockwise.

**Comment by mhosken** [comment]
For which languages? (Please use language codes).

**Comment by cheuk879** [comment]
lpo as stated in subject

**Comment by mhosken** [comment]
Duh, sorry. Thanks.

**Comment by cheuk879** [comment]
Similar to Issue #54 , user based their original feedback on old build.  Passed them glyph images of build 194 on 2019-05-31 & today they expressed satisfaction with the shapes they saw.
