### ISSUE TITLE
[sfm] S & E need lowering; K may need raising

### ISSUE THREAD

**Issue by cheuk879** [silnrsi/font-shimenkan#53]
![plrd-sfm-tones-k-toolow](https://user-images.githubusercontent.com/10625598/58597860-1d6cea00-8237-11e9-86ca-9a7fd8792234.png)
K position is noticeably below the red centre line.  Theoretically it should be shifted up.  BUT as in Issue #33 , sfm--in fact every group that uses S--wants flush top for S.  So we actually need to lower S & E (& maybe shift K a little higher if needed).

**Comment by cheuk879** [comment]
sfm has just confirmed the positions below are what they want:
![plrd-sfm-tone-pos-ideal](https://user-images.githubusercontent.com/10625598/59152272-eef0cb00-89fd-11e9-9806-0c7676f1ddd0.png)
So K does need raising a bit, in addition to lowering S & E.

**Comment by jvgaultney** [comment]
E & K have now been adjusted to even out their vertical position with respect to S and F positions. Switching to flush top positioning for S is a separate issue. #33 

![image](https://user-images.githubusercontent.com/4226750/60374110-b049a180-99fa-11e9-9b61-6512c8ab43e7.png)
![image](https://user-images.githubusercontent.com/4226750/60374128-c5becb80-99fa-11e9-953b-0a962a87f438.png)
![image](https://user-images.githubusercontent.com/4226750/60374133-cbb4ac80-99fa-11e9-9e86-f01e676ba52d.png)
![image](https://user-images.githubusercontent.com/4226750/60374142-d3745100-99fa-11e9-839a-fb988395a5e4.png)

Is this now good?

**Comment by cheuk879** [comment]
Looks beautiful :)
