### ISSUE TITLE
Vowels not rendering in Top position for one specific sequence

### ISSUE THREAD

**Issue by Nathan22Miles** [silnrsi/font-shimenkan#55]
I downloaded and installed the Shimenkan-Regular.ttf font from Fonts_Shimenkan_results_195.zip on my Win10 machine.

In general I think it renders well at least as far as a non-reader of the language can tell.

There is one specific sequence however that does not AFAICT render correctly when displaying it in Chrome (which is important because it is the same(ish?) rendering engine used by Paratext 8 which is having the same problem.

Here is an html file that exhibits the problem
[test.zip](https://github.com/silnrsi/font-shimenkan/files/3273811/test.zip)

Here is how it renders on my machine
![image](https://user-images.githubusercontent.com/4006180/59226863-8e969080-8b99-11e9-853a-3a5c6f5a9e30.png)

In the attached image everything in the first line is correct. I include this just to show that the web page renders most sequences correctly. In the second line however, the vowels should be in the top position. Oddly, if you copy the second line and paste it into WordPad and set to use the same font it renders correctly!

Also odd is that Paratext mis-renders the text a bit differently. It places the vowels on the base line like chrome but both vowels are rendered immediately to the right of the consonant so that they overly each other.

Thank you for all your excellent work on this font!

**Comment by kienwt** [comment]
The ICU in PT8.0 does not handle the new Unicode 12 characters which includes 16F82 in your second line. Try replacing icuuc58.dll in the Firefox folder with the hacked file from [icuuc58.zip](https://github.com/silnrsi/font-shimenkan/files/3274245/icuuc58.zip) which results in the image below in PT8.

![with_hacked_dll](https://user-images.githubusercontent.com/18396131/59235019-fd1f3100-8c21-11e9-982d-ae6872c6b756.PNG)

**Comment by cheuk879** [comment]
@Nathan22Miles : Is the hack working for you?  If so, pls. close the issue.

**Comment by Nathan22Miles** [comment]
I believe that resolves the problem. Thank you for your help.
