### ISSUE TITLE
[ygp] 16F5C, 16F60, 16F73, (16F74): 'C'-bowl inner arm needs to be shorter

### ISSUE THREAD

**Issue by cheuk879** [silnrsi/font-shimenkan#56]
![ygp-16f5c_60_73](https://user-images.githubusercontent.com/10625598/59954206-c2e33a00-9440-11e9-870e-f6658326c683.png)
Above are glyph shapes users have been using & prefer.  In glyphs 1, 2, & 4, notice the internal side of the bowl that joins the vertical tail is shorter than the external side.
For comparison, the default in build 194 has a symmetric bowl as shown below:
![plrd-ygp-16f5c_60_73-build194](https://user-images.githubusercontent.com/10625598/59955415-42740780-9447-11e9-93fc-e7f99d1a60a7.png)

**Comment by cheuk879** [comment]
BTW, 16F74 is another in this series with the same base shape but different orientation.
![plrd-16f74](https://user-images.githubusercontent.com/10625598/59971699-77af5100-953e-11e9-8522-057d6d51a160.png)
It's not in their alphabet, but a corresponding variant may be provided if it is desired to complete the series.

**Comment by jvgaultney** [comment]
This style was the default style in Shishan, however MiaoUnicode (which has informed most of the design decisions for Shimenkan) does not do this. We can add in a whole set of alternate glyphs and add yet another feature to substitute them, but it may affect more than just those four. Note the following shapes from Shishan:

![image](https://user-images.githubusercontent.com/4226750/60269513-8010de80-98e6-11e9-8e7e-589b7bc1569c.png)

Should this new feature affect the five other glyphs shown? And is this [ygp] only?

**Comment by cheuk879** [comment]
After a year of feedback collection only [ygp] came up with this, & that for only the captioned chars.  The other chars are not used by them, & those groups who do use them have never remarked there's anything wrong with our Shimenkan glyph samples.  So I guess we can just focus on the captioned chars.

**Comment by jvgaultney** [comment]
Great - thanks - that's helpful. I'll add only the three that are definitely needed, and add them to the [ygp] specific feature. Glyphs needed: u16F5C.ygp, u16F60.ygp, u16F73.ygp.

**Comment by jvgaultney** [comment]
Needed to add .mark.ygp versions too, for a total of 6 glyphs. Here are the designs in all weights:
![image](https://user-images.githubusercontent.com/4226750/61252521-b4ddbc00-a755-11e9-878f-f3481e05cb37.png)
![image](https://user-images.githubusercontent.com/4226750/61252547-c7f08c00-a755-11e9-9cea-14a6330f8901.png)
![image](https://user-images.githubusercontent.com/4226750/61252565-dd65b600-a755-11e9-8810-7f889dc05118.png)

**Comment by jvgaultney** [comment]
Please review these and let us know if they are OK.

**Comment by cheuk879** [comment]
Looks great :)
