### ISSUE TITLE
[sfm] Shimenkan MAS - Some consonants + vowel + 16F90 no longer positioned properly

### ISSUE THREAD

**Issue by kienwt** [silnrsi/font-shimenkan#64]
Starting in build #217, using Shimenkan MAS, some combinations with 16F90 are no longer positioned properly. Shimenkan Test displays OK.

Raw text:
[sfm_consonant_vowel_16F90.txt](https://github.com/silnrsi/font-shimenkan/files/3404785/sfm_consonant_vowel_16F90.txt)

Libreoffice image:
![image](https://user-images.githubusercontent.com/18396131/61429834-a66ddc80-a8dc-11e9-9766-2a02e7a5c48a.png)

**Comment by mhosken** [comment]
I'm having trouble reproducing this. Is libo using the latest font? It also doesn't make theoretical sense, but that doesn't hold much water :)

**Comment by kienwt** [comment]
Seeing the same thing with LO 6.2.4.2 (x64), Notepad, and Notepad++ on Windows 10

**Comment by mhosken** [comment]
I think this may be a script category problem given chars 16F45-16F4A are new to Unicode and so libo doesn't know to do the right grouping. Not sure why it manifests just the way it does. But I can also make 16F8F fail, for example. Everything is fine for 16F40 as a base, as another example.

**Comment by mhosken** [comment]
There are a number of missing APs on bases. Particularly SR (which I think I have them covered) and FR (not covered). Committed at least fixes the above problem.

**Comment by mhosken** [comment]
These are fixed now.
