### ISSUE TITLE
[hmdd] Unkern asp & dot

### ISSUE THREAD

**Issue by cheuk879** [silnrsi/font-shimenkan#66]
Users do **not** want kerning for asp or dot (ignore font style):
![plrd-hmdd-aspdot-nokern](https://user-images.githubusercontent.com/10625598/61521097-c11f7e80-a9cc-11e9-98af-54561eecce12.png)

But the asp & dot are all kerned in build 222:
![plrd-test-kern-aspdot-hmdd-222](https://user-images.githubusercontent.com/10625598/61521020-959c9400-a9cc-11e9-9a16-1a557dc25914.png)

Compare Build 194 where at least the last line was correct:
![plrd-test-kern-aspdot-hmdd-194](https://user-images.githubusercontent.com/10625598/61521557-b74a4b00-a9cd-11e9-9058-233c1d07004a.png)

**Comment by mhosken** [comment]
It seems that hmdd wants its vowels flush right just like ygp in which case in the chart hmdd needs to indicate that its F positioning needs to be FR. Please check that this is what they want. I'll commit a test for this. If this is not the behaviour wanted then we need a deeper discussion.

**Comment by jvgaultney** [comment]
If hmdd does want vowels and asp flush right then we would just need to add them to flush right feature as mhosken points out. That would not change the position of the dot, though, as the dot is part of the letter itself - The cons+dot combination is an hmdd-specific variant of warted cons. So we need to make both changes.

**Comment by jvgaultney** [comment]
I have now done these changes, although the results need visual testing. Aligning the vowels to appear aligned with the dot has some complexities.

**Comment by jvgaultney** [comment]
Seems to be aligning well now:
![image](https://user-images.githubusercontent.com/4226750/61549357-b5bd6900-aa47-11e9-9c7a-71f7f966de83.png)

**Comment by cheuk879** [comment]
Thanks!  This looks much better than before.  It is possible to shift the V a little bit left &/or the dot a little bit right so that the two will appear more flush?

**Comment by jvgaultney** [comment]
We can't move the dot - it's part of the letter, not a separate positionable mark like the asp.

I could make the V in the last four combinations shown above kern inside the consonant, however that seems to be in contradiction with your first request:

> Users do **not** want kerning for asp or dot (ignore font style):

It's also not what is shown in a sample you provided earlier:

![image](https://user-images.githubusercontent.com/4226750/61941808-1ab91780-af90-11e9-84d5-bbef50e3e2b9.png)

Note that it is not possible with the current attachment mechanism to make the *right* side of the V align with the *right* side of the dot. If I move the F position back to the left again for those dotted consonants, all vowels will move to the left the same amount under those dotted consonants. IOW the dot and vowel would never be consistently aligned either on the right or left sides, as the vowels are not the same width. They would also not be consistent with the asp alignment.

Please confirm ASAP whether you want *all* F position vowels to fully kern under dotted consonants, as **they will then no longer be aligned with the dot on the right or left sides**.

**Comment by cheuk879** [comment]
For <C, asp/dot>, indeed users do not want kerning for the asp or the dot, i.e., even when there's space in the upper right corner of C like 'L', the asp/dot should not be kerned/tucked in.  However, for <asp/dot, V>, they do want V kerned under the asp/dot so that the left sides of both asp/dot & V fall on the same vertical line (see planning doc) as shown in the scan you included above.  (BTW, they have never indicated a desire to have the right sides of V & asp/dot to be on the same line, so this is a non-issue for them.)

As it is, build 233 is far superior to build 222 or 194, as the left side of V is almost as far left as the left side of the dot:
![plrd-test-kern-cdotv-hmdd](https://user-images.githubusercontent.com/10625598/61986674-badd6380-afc5-11e9-93e0-b06887796a8f.png)
The question is whether it's technically possible to adjust still a little further, either by shifting V just a little further left (via kerning/AP) or by shifting the dot just a little further right (when composing the glyph from the dot + C) so that the left sides of both V & dot fall on the same line.  In any case, I agree the "flush right" feature should be off lest it negate the kerning under the dot.

While the dot & V are almost aligned, the asp is still not so per build 233:
![plrd-test-kern-caspv-hmdd](https://user-images.githubusercontent.com/10625598/61986692-d5174180-afc5-11e9-80ac-0589fa68b721.png)
As seen above, the asp is still kerned into C whereas user preference is no kerning even when there's space in the upper right corner.  And again, <asp, V> need to have both their left sides on the same line.

**Comment by jvgaultney** [comment]
As for the C+dot+V@F:
I can adjust the position of V some more, although there is no way to make it numerically perfectly aligned with the dot on the left side and visually appear always aligned. It's a well known optical illusion. I will change this to be numerically rather than visually aligned and hope for the best!

**Comment by jvgaultney** [comment]
As for the C+asp+V@F:
This will require changes to the OT code. The dot is part of the letter itself, whereas the asp is a separate floating thing.

**Comment by jvgaultney** [comment]
Position adjusted for C+dot+V@F. I still did not make it numerically aligned, as that really would have looked odd. However I did tweak all the V to the left a bit, so that in most cases it will appear better aligned.

I also noticed that all the W APs were badly positioned in dotted glyphs, so moved them to the same position as F.

**Comment by mhosken** [comment]
HMDD now follows YGP in everything hangs right. I think that we need to adjust the FR AP in the dot consonants to be the same as F, sans jiggle shift. OK, _add_ an FR AP. We can decide if we want to move F back or not later. But F doesn't now get used in dotted consonants.

**Comment by jvgaultney** [comment]
That's fine, but you missed a whole lot of dotted glyphs when adding FR (such as u16F1D.dot). BTW don't forget u16F05.hmdd, u16F11.hmdd, u16F15.hmdd,u16F24.hmdd. 

Please add the missing ones. You may as well also delete F on these and other .dot glyphs if we're not using them anymore.

**Comment by cheuk879** [comment]
Per build 242, kerning behaviours for asp & dot are mostly fixed except for the following combos in red:
![plrd-test-kern-dot-err-242](https://user-images.githubusercontent.com/10625598/62671786-03ddd200-b94d-11e9-94e6-fda9364031f4.png)
