### ISSUE TITLE
[hmd, hmz] Asp needs to be kerned for even when V is at H

### ISSUE THREAD

**Issue by jvgaultney** [silnrsi/font-shimenkan#68]
Asp needs to be kerned for [hmd] & [hmz] even when V is at H.

**Comment by cheuk879** [comment]
![plrd-test-kern-asp+](https://user-images.githubusercontent.com/10625598/62035545-ed918280-b1a4-11e9-9930-f946585e21b7.png)
Per build 233, those asp in red has no kerning & need to be kerned (tucked in).
