### ISSUE TITLE
Flush right floor position not working consistently

### ISSUE THREAD

**Issue by jvgaultney** [silnrsi/font-shimenkan#69]
[sfm] desires no kerning for V even at F, but currently at least 2 warted chars (16F0B & 16F38) have been spotted with V kerned inside it. This is an AP position problem.

**Comment by cheuk879** [comment]
Another one with V kerning spotted: 16F22
![plrd-test-kern-sfm](https://user-images.githubusercontent.com/10625598/62044765-92698b00-b1b8-11e9-907d-c66371f4bf34.png)
Those 3 in red should have no kerning.

**Comment by jvgaultney** [comment]
I fixed all of these and even ones you haven't spotted yet. Please check build 236.
