### ISSUE TITLE
u16F54 (and u16F66?) should sit on baseline at F position

### ISSUE THREAD

**Issue by jvgaultney** [silnrsi/font-shimenkan#70]
Currently u16F54 is top-aligned when at S position, but is centered in the box at F position. It should instead sit on the baseline at F position. Current position: 

![image](https://user-images.githubusercontent.com/4226750/62033234-6ca5ab80-b1e3-11e9-8b03-de4b9c17f64e.png)

Should this positioning also be applied to u16F66?

This will require moving the outline lower and moving all the non-F/FR APs lower by the same amount.

**Comment by cheuk879** [comment]
Yes, both should sit on the baseline.  One catch, however, is [lpo] wants 16F54 to be centred when following 16F61.  See Issue #54 .

**Comment by jvgaultney** [comment]
These two glyphs will now sit on the baseline at F position. All other positions are unaffected.

However that will undo #54 at F position for [lpo]. Do we need to do a special lookup just to give u16F61+u16F54/u16F61+u16F66 special F positioning just for [lpo]? And where should 54/66 be positioned for [lpo] when it's not after u16F61?

**Comment by cheuk879** [comment]
Special lookup would be appreciated.  When not after u16F61, normal positioning applies (i.e., top-aligned at S, bottom-aligned at F).

**Comment by jvgaultney** [comment]
Users have confirmed that this fix is working now. The special case of u16F61+ is a separate issue #54
