### ISSUE TITLE
Spacing problems when V is tucked under asp

### ISSUE THREAD

**Issue by jvgaultney** [silnrsi/font-shimenkan#75]
We have an odd spacing problem when V is tucked under asp. Affects more than one language, including default:
![image](https://user-images.githubusercontent.com/4226750/63087030-19ed2300-bf49-11e9-890c-f68f293914cd.png)
The actual glyphs are fine, and spacing after asp is fine otherwise.

**Comment by mhosken** [comment]
Addressed with forward cursive attachment issues

**Comment by jvgaultney** [comment]
OK that problem is fixed, however there is now a different problem with spacing in build 261:

![image](https://user-images.githubusercontent.com/4226750/63097120-8545ed80-bf67-11e9-9e98-a2ea80c61301.png)

It seems that when a V is tucked under an asp some extra space is added after the V.

**Comment by cheuk879** [comment]
I think the issue here is rather there's too much space **before** the V.  In the 2nd set, combos 1 & 3, V+ is not really flush right with C but is separated by a noticeable gap, & for combo 2, a more noticeable gap lies between LHS of V & RHS of asp.  And in combo 4, LHS of VV should align to RHS of asp.

**Comment by mhosken** [comment]
The position of the vowels is such that they align in all right hand tone positions, particularly S. This does result in vowels in lower positions, particularly F, looking hung out a bit. Perhaps we could tighten the S/SR to reduce that a little. But it probably wouldn't be enough. Is my assumption that the concern is that vowels in all tone positions align correct? Or do we want the lower vowels (W/F) to align the bounding boxes (left of vowel to right of asp)? But S will still stick out.

**Comment by jvgaultney** [comment]
You're mixing up two issues here. I'm moving your comments about the alignment of asp and V into issue #79. 

This has to do with extra space being added between syllables:

![image](https://user-images.githubusercontent.com/4226750/63155683-fab6ca00-c00a-11e9-88a9-8dc023028260.png)

There is not any extra space character in the text stream - something is messing up the spacing.

**Comment by jvgaultney** [comment]
Fixed in build 271!

![image](https://user-images.githubusercontent.com/4226750/63162455-753b1600-c01a-11e9-8503-341138c6ff49.png)
