### ISSUE TITLE
[hmdd] Asp overlays dot on dotted consonants

### ISSUE THREAD

**Issue by jvgaultney** [silnrsi/font-shimenkan#76]
When an asp follows a dotted consonant the asp overlays the dot:

![image](https://user-images.githubusercontent.com/4226750/63095618-9856be80-bf63-11e9-82e0-2db28587ba59.png)

This is due to the change to right alignment. We didn't initially think that SR/SRT APs were needed on dotted glyphs so they are not there. Fix is to add those to all dotted glyphs.

**Comment by jvgaultney** [comment]
Here's the result of the fix:

![image](https://user-images.githubusercontent.com/4226750/63121433-55fda380-bf9c-11e9-9e85-9b0660ff7a4b.png)

Note that the V aligns with the _dot_, not the _asp_ here. You've never told us what should happen when there's both a dot+asp+V for hmdd. Is this correct (or at least acceptable for v1.0)?

**Comment by cheuk879** [comment]
This was not mentioned before because they don't use them together (rf. the charts I sent you), but thank you for being cautious.  I'd gladly accept what is shown, leaving this option viable for some future generations to come :)

**Comment by jvgaultney** [comment]
OK thanks. Please understand that all the explanatory test in the charts you sent is in Chinese, so I can only guess at the meaning. Even if I knew that the charts were comprehensive and showed every possible combination in the language that might not include unusual combinations for loan words. Those often lie outside the normal phonemics/graphemics of a language.
