### ISSUE TITLE
V at W does not fully tuck into some consonants

### ISSUE THREAD

**Issue by jvgaultney** [silnrsi/font-shimenkan#77]
When V is at W the V does not tuck in far enough when the consonant is open on the lower right. It should tuck in as far as when at F. Moving the AP in will, however, cause collisions in the bold weights, but that may be better than having the regular and book weights look odd. Collisions can be worked out post-1.0. 

![image](https://user-images.githubusercontent.com/4226750/63096579-2f247a80-bf66-11e9-857c-ecc192999d8a.png)

**Comment by jvgaultney** [comment]
Fix seems to have worked:

![image](https://user-images.githubusercontent.com/4226750/63120473-3f564d00-bf9a-11e9-9cde-8c3a96ded78c.png)

As suspected, the Book Bold shows some collisions, although they are not too bad. Here is a sample of a few:

![image](https://user-images.githubusercontent.com/4226750/63120656-9c520300-bf9a-11e9-88cb-b7c56f4a9be6.png)
![image](https://user-images.githubusercontent.com/4226750/63120759-d9b69080-bf9a-11e9-9950-a9ab5e6aaa88.png)

The second set is the worst of them, but I'm inclined to leave it because it improves the normal Book weight:

![image](https://user-images.githubusercontent.com/4226750/63120917-3b76fa80-bf9b-11e9-89bd-543f834cac0b.png)

Of course adding an asp in there will make it all that much worse, but the only remedy for that is to make all the V flush right at W.

@cheuk879 is this OK?

**Comment by cheuk879** [comment]
Yes!  Book Bold actually doesn't look bad.  It's still legible.  Thanks for your hard work!
