### ISSUE TITLE
[hmd] right alignment against a stem

### ISSUE THREAD

**Issue by mhosken** [silnrsi/font-shimenkan#80]
The instructions for HMD is that a vowel in floor position following an asp is to right align with the asp such that the right of the vowel is under the right of the asp. But if there is a vertical stem there (say U+16F00) then one gets a collision. What to do?

**Comment by mhosken** [comment]
Presuming we don't right align, but left align instead if there is a hard stem that could collide.

**Comment by cheuk879** [comment]
RHS to RHS alignment applies only to cases with C open at bottom-right.  If a C is not open there, the [hmd] default applies: tuck where possible, which is equivalent to LHS to LHS alignment....ah you're updating just now...so yes, your assumption is correct.

**Comment by jvgaultney** [comment]
There seems to be an odd spacing issue with this that definitely needs fixing for 1.0. There is an inconsistency between [yna] and [hmd]. In both cases for V@F+asp the RHS of V and RHS of asp now align, but the space after the cluster is more (and incorrect) for [hmd]:

![image](https://user-images.githubusercontent.com/4226750/63231631-5e611300-c216-11e9-9972-96ce631a0e4d.png)
![image](https://user-images.githubusercontent.com/4226750/63231637-6faa1f80-c216-11e9-8150-d48eb792a7a7.png)

**Comment by jvgaultney** [comment]
Fix confirmed in build 279
