### ISSUE TITLE
Vowel in head position does not render properly in Microsoft Word 2013, 2016, 365

### ISSUE THREAD

**Issue by kienwt** [silnrsi/font-shimenkan#82]
Vowel in head position does not render properly in Microsoft Word 2013, 2016, 365

It displays as expected in Notepad and LibreOffice 6.2.5.2 (x64) on Windows 10 Pro.

Have searched online to see if there's something else that needs to be enabled for OpenType but haven't found anything.

Raw text:
[raw.txt](https://github.com/silnrsi/font-shimenkan/files/3523750/raw.txt)

Word docx:
[head_position_test.docx](https://github.com/silnrsi/font-shimenkan/files/3527810/head_position_test.docx)

Comparison of OpenType fonts:
![head_position](https://user-images.githubusercontent.com/18396131/63406038-8464ef80-c39d-11e9-872e-ff73d736d988.png)

Renders as expected in preview mode:
![preview](https://user-images.githubusercontent.com/18396131/63406043-875fe000-c39d-11e9-8af6-dcf3b561e86e.png)

Word options to enable OpenType:
![image](https://user-images.githubusercontent.com/18396131/63406204-0b19cc80-c39e-11e9-86d7-525e8cfcf0e2.png)

**Comment by mhosken** [comment]
Does ShimenkanTest work?

**Comment by kienwt** [comment]
> Does ShimenkanTest work?

ShimenkanTest renders the same as Shimenkan MAS Test

**Comment by jvgaultney** [comment]
So what font is Shimenkan-OT?

**Comment by kienwt** [comment]
> So what font is Shimenkan-OT?

This is the MiaoUnicode font with OT added, https://github.com/silnrsi/MiaoUnicode/tree/ot

**Comment by mhosken** [comment]
This issue is addressed in ce3cd886b59f463ea7ba0e0ff218e73d08eb9411 The change requires head and foot inter cluster kerning to be reviewed.

**Comment by jvgaultney** [comment]
Yes - this brings back collisions between clusters, so #31 has been reopened. Fixing that will have to wait until after 1.0 - sorry!

**Comment by jvgaultney** [comment]
It also causes a spacing problem to return, as noted in #50. That one we're going to try and fix for 1.0.
